# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 5  # Hz

    hand_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

hand_controller:
  ros__parameters:
    joints:
      - shoulder_psi
      - shoulder_theta
      - elbow
      - wrist_theta
      - wrist_psi
    command_interfaces:
      - position
    state_interfaces:
      - position

gripper_controller:
  ros__parameters:
    joints:
      - left_knuckle
    command_interfaces:
      - position
    state_interfaces:
      - position
